name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python 3.9 (matching your Dockerfile)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r app/requirements.txt

      # Run backend tests (assuming pytest, adjust if different)
      - name: Run backend tests
        run: |
          cd backend
          pip install pytest # Install pytest if not in requirements.txt
          pytest # Adjust if your test command or directory differs

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js 20 (matching your Dockerfile)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Run frontend tests (assuming npm test, adjust if different)
      - name: Run frontend tests
        run: |
          cd frontend
          npm test # Adjust if your test command differs (e.g., npm run test)

  build-and-push:
    needs: [test-backend, test-frontend] # Only run if tests pass
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy on push to main

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push backend image
      - name: Build and push backend image
        run: |
          docker build -t whitewarlock/greenpulse-backend:${{ github.sha }} ./backend
          docker tag whitewarlock/greenpulse-backend:${{ github.sha }} whitewarlock/your-app-backend:latest
          docker push whitewarlock/greenpulse-backend:${{ github.sha }}
          docker push whitewarlock/greenpulse-backend:latest

      # Build and push frontend image
      - name: Build and push frontend image
        run: |
          docker build -t whitewarlock/greenpulse-frontend:${{ github.sha }} ./frontend
          docker tag whitewarlock/greenpulse-frontend:${{ github.sha }} whitewarlock/your-app-frontend:latest
          docker push whitewarlock/greenpulse-frontend:${{ github.sha }}
          docker push whitewarlock/greenpulse-frontend:latest
